// phishingList.js
// List of phishing, pirated, and hijacked journal domains/keywords

const phishingList = [
    'phishing-site.org',
    'malicious-example.com',
    'phishtank.org',
    'ibomma',
    '1xbet.com',
    'bet365.com',
    'betway.com',
    'parimatch.com',
    'dafabet.com',
    '10cric.com',
    'melbet.com',
    'betfair.com',
    'betwinner.com',
    '22bet.com',
    'betika.com',
    'bet9ja.com',
    'betpawa.com',
    'betking.com',
    'sportybet.com',
    'ibommaone.in',
    'movierulz',
    'filmyzilla',
    'tamilyogi',
    'moviesda',
    'bolly4u',
    'khatrimaza',
    'jalshamoviez',
    '9xmovies',
    'worldfree4u',
    'hdhub4u',
    'desiremovies',
    'okjatt',
    'pagalmovies',
    'skymovieshd',
    'extramovies',
    'mkvcinemas',
    'katmoviehd',
    'adalya',
    'aegaeum',
    'agrociencia',
    'arctic',
    'boreal environment research',
    'ccamlr science',
    'high technology letters',
    'international medical journal',
    'journal of southwest jiaotong university',
    'journal of talent development and excellence',
    'journal of university of shanghai for science and technology',
    'journal of xi’an shiyou university',
    'journal of xi’an university of architecture & technology',
    'journal of xidian university',
    'liverpool university press',
    'opción',
    'paideuma journal of research',
    'polish polar research',
    'preslia journal',
    'revista de educacion',
    'revistas electrónicas uach',
    'technology reports of kansai university',
    'test: engineering & management',
    'turkish journal of physiotherapy and rehabilitation',
    'archivesdesci.com',
    'wulfeniajournal.at',
    'jstr.org.in',
    'ijbst',
    'ijact.org'
    // Add more as needed
];
